dspace:
    build: ./dspace
    links:
        - postgres:db
    ports:
        - "80:8080"

postgres:
    image: postgres:9.4
    environment:
        - POSTGRES_USER=dspace
        - POSTGRES_PASSWORD=dspace
        - POSTGRES_DB=dspace
